In [2]:
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

print("Pandas:", pd.__version__)
print("Scikit-learn:", sklearn.__version__)
print("Mediul de lucru este pregătit!")

Pandas: 2.2.3
Scikit-learn: 1.6.1
Mediul de lucru este pregătit!

In [4]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("products.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'products.csv'

In [8]:
import os

print(os.listdir())

['.config', 'drive', 'sample_data']

In [9]:
from google.colab import files

uploaded = files.upload()

Saving IMLP6_TASK_03-products.csv to IMLP6_TASK_03-products.csv

In [10]:
print(uploaded.keys())

dict_keys(['IMLP6_TASK_03-products.csv'])

In [12]:
df = pd.read_csv("IMLP6_TASK_03-products.csv")

df.head()

,product ID,Product Title,Merchant ID,Category Label,_Product Code,Number_of_Views,Merchant Rating,Listing Date
0,1,apple iphone 8 plus 64gb silver,1,Mobile Phones,QA-2276-XC,860.0,2.5,5/10/2024
1,2,apple iphone 8 plus 64 gb spacegrau,2,Mobile Phones,KA-2501-QO,3772.0,4.8,12/31/2024
2,3,apple mq8n2b/a iphone 8 plus 64gb 5.5 12mp sim...,3,Mobile Phones,FP-8086-IE,3092.0,3.9,11/10/2024
3,4,apple iphone 8 plus 64gb space grey,4,Mobile Phones,YI-0086-US,466.0,3.4,5/2/2022
4,5,apple iphone 8 plus gold 5.5 64gb 4g unlocked ...,5,Mobile Phones,NZ-3586-WP,4426.0,1.6,4/12/2023

In [13]:
df.head()

,product ID,Product Title,Merchant ID,Category Label,_Product Code,Number_of_Views,Merchant Rating,Listing Date
0,1,apple iphone 8 plus 64gb silver,1,Mobile Phones,QA-2276-XC,860.0,2.5,5/10/2024
1,2,apple iphone 8 plus 64 gb spacegrau,2,Mobile Phones,KA-2501-QO,3772.0,4.8,12/31/2024
2,3,apple mq8n2b/a iphone 8 plus 64gb 5.5 12mp sim...,3,Mobile Phones,FP-8086-IE,3092.0,3.9,11/10/2024
3,4,apple iphone 8 plus 64gb space grey,4,Mobile Phones,YI-0086-US,466.0,3.4,5/2/2022
4,5,apple iphone 8 plus gold 5.5 64gb 4g unlocked ...,5,Mobile Phones,NZ-3586-WP,4426.0,1.6,4/12/2023

In [14]:
df.head(10)

,product ID,Product Title,Merchant ID,Category Label,_Product Code,Number_of_Views,Merchant Rating,Listing Date
0,1,apple iphone 8 plus 64gb silver,1,Mobile Phones,QA-2276-XC,860.0,2.5,5/10/2024
1,2,apple iphone 8 plus 64 gb spacegrau,2,Mobile Phones,KA-2501-QO,3772.0,4.8,12/31/2024
2,3,apple mq8n2b/a iphone 8 plus 64gb 5.5 12mp sim...,3,Mobile Phones,FP-8086-IE,3092.0,3.9,11/10/2024
3,4,apple iphone 8 plus 64gb space grey,4,Mobile Phones,YI-0086-US,466.0,3.4,5/2/2022
4,5,apple iphone 8 plus gold 5.5 64gb 4g unlocked ...,5,Mobile Phones,NZ-3586-WP,4426.0,1.6,4/12/2023
5,6,apple iphone 8 plus gold 5.5 64gb 4g unlocked ...,6,Mobile Phones,SB-2202-CH,3444.0,1.6,11/27/2022
6,7,apple iphone 8 plus 64 gb space grey,7,Mobile Phones,QJ-3229-QP,3171.0,1.2,3/29/2022
7,8,apple iphone 8 plus 64gb space grey,8,Mobile Phones,ES-1396-OR,2919.0,4.5,5/21/2024
8,9,apple iphone 8 plus 64gb space grey,9,Mobile Phones,VU-2032-FY,130.0,3.4,5/11/2022
9,10,apple iphone 8 plus 64gb space grey,10,Mobile Phones,WI-6394-GG,1685.0,3.8,2/9/2024

In [15]:
df.shape

(35311, 8)

In [16]:
df.columns

Index(['product ID', 'Product Title', 'Merchant ID', ' Category Label',
       '_Product Code', 'Number_of_Views', 'Merchant Rating',
       ' Listing Date  '],
      dtype='object')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35311 entries, 0 to 35310
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   product ID       35311 non-null  int64
 1   Product Title    35139 non-null  object
 2   Merchant ID      35311 non-null  int64
 3    Category Label  35267 non-null  object
 4   _Product Code    35216 non-null  object
 5   Number_of_Views  35297 non-null  float64
 6   Merchant Rating  35141 non-null  float64
 7    Listing Date    35252 non-null  object
dtypes: float64(2), int64(2), object(4)
memory usage: 2.2+ MB

In [18]:
df.isnull().sum()

product ID           0
Product Title      172
Merchant ID          0
 Category Label     44
_Product Code       95
Number_of_Views     14
Merchant Rating    170
 Listing Date       59
dtype: int64

In [19]:
df["Category Label"].value_counts()

KeyError: 'Category Label'

In [20]:
print(df.columns.tolist())

['product ID', 'Product Title', 'Merchant ID', ' Category Label', '_Product Code', 'Number_of_Views', 'Merchant Rating', ' Listing Date  ']

In [21]:
df.columns = df.columns.str.strip()

In [22]:
print(df.columns.tolist())

['product ID', 'Product Title', 'Merchant ID', 'Category Label', '_Product Code', 'Number_of_Views', 'Merchant Rating', 'Listing Date']

In [23]:
df["Category Label"].value_counts()

Category Label
Fridge Freezers     5495
Washing Machines    4036
Mobile Phones       4020
CPUs                3771
TVs                 3564
Fridges             3457
Dishwashers         3418
Digital Cameras     2696
Microwaves          2338
Freezers            2210
fridge               123
CPU                   84
Mobile Phone          55
Name: count, dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df_clean = df.copy()

In [26]:
df_clean.isnull().sum()

product ID           0
Product Title      172
Merchant ID          0
Category Label      44
_Product Code       95
Number_of_Views     14
Merchant Rating    170
Listing Date        59
dtype: int64

In [27]:
(df_clean.isnull().mean() * 100).round(2)

product ID         0.00
Product Title      0.49
Merchant ID        0.00
Category Label     0.12
_Product Code      0.27
Number_of_Views    0.04
Merchant Rating    0.48
Listing Date       0.17
dtype: float64

In [28]:
df_clean = df_clean.dropna(
    subset=["Product Title", "Category Label"]
)

In [30]:
df_clean["Product Title"] = df_clean["Product Title"].astype(str).str.strip()

df_clean["Category Label"] = df_clean["Category Label"].astype(str).str.strip()

df_clean = df_clean[
    (df_clean["Product Title"] != "") &
    (df_clean["Category Label"] != "")
]

In [31]:
print("Duplicate înainte:", df_clean.duplicated().sum())

df_clean = df_clean.drop_duplicates()

print("Duplicate după:", df_clean.duplicated().sum())

Duplicate înainte: 0
Duplicate după: 0

In [32]:
df_clean["Product Title"] = (
    df_clean["Product Title"]
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [33]:
print("Dimensiune inițială:", df.shape)
print("Dimensiune după curățare:", df_clean.shape)

print("\nValori lipsă:")
print(df_clean.isnull().sum())

print("\nPrimele produse:")
display(df_clean.head())

Dimensiune inițială: (35311, 8)
Dimensiune după curățare: (35096, 8)

Valori lipsă:
product ID           0
Product Title        0
Merchant ID          0
Category Label       0
_Product Code       94
Number_of_Views     14
Merchant Rating    170
Listing Date        58
dtype: int64

Primele produse:

,product ID,Product Title,Merchant ID,Category Label,_Product Code,Number_of_Views,Merchant Rating,Listing Date
0,1,apple iphone 8 plus 64gb silver,1,Mobile Phones,QA-2276-XC,860.0,2.5,5/10/2024
1,2,apple iphone 8 plus 64 gb spacegrau,2,Mobile Phones,KA-2501-QO,3772.0,4.8,12/31/2024
2,3,apple mq8n2b/a iphone 8 plus 64gb 5.5 12mp sim...,3,Mobile Phones,FP-8086-IE,3092.0,3.9,11/10/2024
3,4,apple iphone 8 plus 64gb space grey,4,Mobile Phones,YI-0086-US,466.0,3.4,5/2/2022
4,5,apple iphone 8 plus gold 5.5 64gb 4g unlocked ...,5,Mobile Phones,NZ-3586-WP,4426.0,1.6,4/12/2023

In [34]:
df_clean["Category Label"].value_counts()

Category Label
Fridge Freezers     5470
Washing Machines    4015
Mobile Phones       4002
CPUs                3747
TVs                 3541
Fridges             3436
Dishwashers         3405
Digital Cameras     2689
Microwaves          2328
Freezers            2201
fridge               123
CPU                   84
Mobile Phone          55
Name: count, dtype: int64

In [35]:
X = df_clean["Product Title"]
y = df_clean["Category Label"]

print("Număr de titluri:", len(X))
print("Număr de categorii:", y.nunique())

display(X.head())
display(y.head())

Număr de titluri: 35096
Număr de categorii: 13

0                      apple iphone 8 plus 64gb silver
1                  apple iphone 8 plus 64 gb spacegrau
2    apple mq8n2b/a iphone 8 plus 64gb 5.5 12mp sim...
3                  apple iphone 8 plus 64gb space grey
4    apple iphone 8 plus gold 5.5 64gb 4g unlocked ...
Name: Product Title, dtype: object

0    Mobile Phones
1    Mobile Phones
2    Mobile Phones
3    Mobile Phones
4    Mobile Phones
Name: Category Label, dtype: object

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=10000,
    stop_words="english",
    ngram_range=(1, 2)
)

X_tfidf = tfidf.fit_transform(X)

print("Dimensiunea matricei TF-IDF:", X_tfidf.shape)

Dimensiunea matricei TF-IDF: (35096, 10000)

In [37]:
print("Tipul datelor:", type(X_tfidf))
print("Număr de produse:", X_tfidf.shape[0])
print("Număr de caracteristici:", X_tfidf.shape[1])

Tipul datelor: <class 'scipy.sparse._csr.csr_matrix'>
Număr de produse: 35096
Număr de caracteristici: 10000

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [40]:
print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)

print("Training labels:", y_train.shape)
print("Testing labels:", y_test.shape)

Training features: (28076, 10000)
Testing features: (7020, 10000)
Training labels: (28076,)
Testing labels: (7020,)

In [41]:
from sklearn.linear_model import LogisticRegression

In [42]:
model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

In [43]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [44]:
y_pred = model.predict(X_test)

print("Primele 10 predicții:")
print(y_pred[:10])

print("\nCategoriile reale:")
print(y_test.iloc[:10].values)

Primele 10 predicții:
['Fridge Freezers' 'Freezers' 'Fridges' 'Freezers' 'Fridges'
 'Fridge Freezers' 'CPUs' 'TVs' 'Digital Cameras' 'Fridge Freezers']

Categoriile reale:
['Fridge Freezers' 'Freezers' 'Fridges' 'Freezers' 'Fridges'
 'Fridge Freezers' 'CPUs' 'TVs' 'Digital Cameras' 'Fridge Freezers']

In [45]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [46]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", round(accuracy, 4))
print("Accuracy (%):", round(accuracy * 100, 2), "%")

Accuracy: 0.9526
Accuracy (%): 95.26 %

In [47]:
print(classification_report(y_test, y_pred))

                  precision    recall  f1-score   support

             CPU       0.00      0.00      0.00        17
            CPUs       0.98      1.00      0.99       749
 Digital Cameras       1.00      0.99      1.00       538
     Dishwashers       0.94      0.95      0.94       681
        Freezers       0.99      0.92      0.95       440
 Fridge Freezers       0.93      0.95      0.94      1094
         Fridges       0.86      0.90      0.88       687
      Microwaves       0.99      0.96      0.97       466
    Mobile Phone       0.00      0.00      0.00        11
   Mobile Phones       0.95      1.00      0.97       801
             TVs       0.99      0.99      0.99       708
Washing Machines       0.96      0.95      0.95       803
          fridge       0.00      0.00      0.00        25

        accuracy                           0.95      7020
       macro avg       0.74      0.74      0.74      7020
    weighted avg       0.95      0.95      0.95      7020

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [48]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[   0   17    0    0    0    0    0    0    0    0    0    0    0]
 [   0  747    0    0    0    0    0    0    0    2    0    0    0]
 [   0    0  535    0    0    0    0    0    0    2    1    0    0]
 [   0    0    0  645    1    9    9    1    0    1    1   14    0]
 [   0    0    0    3  405    6   18    0    0    2    0    6    0]
 [   0    0    0   10    2 1034   31    0    0    9    1    7    0]
 [   0    0    1    9    2   49  618    0    0    4    0    4    0]
 [   0    0    0    3    0    3    5  447    0    3    2    3    0]
 [   0    0    0    0    0    0    0    0    0   11    0    0    0]
 [   0    0    1    0    0    0    1    0    0  797    2    0    0]
 [   0    0    0    0    0    0    0    0    0   10  698    0    0]
 [   0    0    0   15    0   10   10    3    0    1    3  761    0]
 [   0    0    0    0    0    0   24    0    0    0    0    1    0]]